name: Monorepo CI

on:
  push:
    branches: [main, dev, 'changeset-release/**']
  pull_request:
    branches: [main, dev, 'changeset-release/**']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm config get store-dir)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          if [[ "${{ github.ref }}" == refs/heads/changeset-release/* ]]; then
            echo "Installing with --no-frozen-lockfile for changeset release branch"
            pnpm install --no-frozen-lockfile
          else
            echo "Installing with --frozen-lockfile for stable branch"
            pnpm install --frozen-lockfile
          fi

      - name: Run CI script
        run: ./scripts/ci.sh
